apiVersion: apps/v1
kind: Deployment
metadata:
 name: exam-deployment
 namespace: examnamespace
 labels:
   app: exam
spec:
 replicas: 1
 selector:
   matchLabels:
     app: exam
 template:
   metadata:
     labels:
       app: exam
   spec:
     containers:
       - name: exam
         image: miwgu/exam_backend2:0.0.1
         imagePullPolicy: IfNotPresent