apiVersion: v1
kind: Service
metadata:
 name: exam-service
 namespace: examnamespace
spec:
 selector:
   app: exam
 ports:
   - name: application
     protocol: TCP
     port: 8080
     targetPort: 8080
 type: ClusterIP